[package]
name = "nu_plugin_bg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-errors = "0.40.0"
nu-plugin = "0.40.0"
nu-protocol = "0.40.0"
nu-source = "0.40.0"
